[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gaf"
version = "0.1.0"
description = "Gradient Agreement Filtering Package"
authors = [
  { name="Francois Chaubard", email="fchaubard@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  "torch",
  "torchvision",
  "numpy",
]

[tool.setuptools.packages.find]
where = ["src"]
